sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9u9pA2uZknpUzPyGGi
    access-key-secret: 0ArxMZX01EWLf6CkUpXSF90i4YZ5XD
    bucket-name: java-ai-qinxuwei